"""Build the approved synthetic Kyiv–Lisbon scenario, without a per-rail inventory."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build_rails(length, block):
    """Fill one area; rail sizes create boundaries, annotations never do."""
    if not isinstance(length, (int, float)) or length <= 0 or length % 12.5:
        raise ValueError('Area length must be a positive multiple of 12.5 m')
    if block in ('long-800', 'long-1500'):
        nominal = 800 if block == 'long-800' else 1500
        rails, remaining, full = [], length, 0
        while remaining:
            size = min(nominal, remaining)
            rails.append(size)
            remaining -= size
            full += size == nominal
            # Connect only when another complete long rail fits afterwards.
            if nominal == 800 and full % 5 == 0 and remaining >= nominal + 12.5:
                rails.append(12.5)
                remaining -= 12.5
        return rails
    if block != 'short-25':
        raise ValueError(f'Unknown area block: {block}')
    groups = [(4, 1), (5, 2), (4, 2), (5, 1)]
    units = int(length / 12.5)
    feasible = [True] + [False] * units
    for n in range(1, units + 1):
        feasible[n] = any(n >= 2 * full + short and feasible[n - 2 * full - short]
                          for full, short in groups)
    if not feasible[units]:
        raise ValueError('Reduced area cannot be filled with complete rail groups')
    rails, cursor = [], 0
    while units:
        for shift in range(len(groups)):
            selected = (cursor + shift) % len(groups)
            full, short = groups[selected]
            used = 2 * full + short
            if units >= used and feasible[units - used]:
                rails.extend([25] * full + [12.5] * short)
                units -= used
                cursor = (selected + 1) % len(groups)
                break
    return rails


def build_route():
    itinerary = [
        ('UA', 'Kyiv', 0), ('UA', 'Shepetivka', 300), ('UA', 'Lviv', 580),
        ('PL', 'Przemyśl', 680), ('PL', 'Kraków', 930), ('PL', 'Katowice', 1010),
        ('PL', 'Wrocław', 1210), ('DE', 'Dresden', 1480), ('DE', 'Leipzig', 1600),
        ('DE', 'Frankfurt am Main', 1980), ('FR', 'Strasbourg', 2200),
        ('FR', 'Paris', 2690), ('FR', 'Bordeaux', 3270), ('FR', 'Hendaye', 3500),
        ('ES', 'Irún', 3505), ('ES', 'Burgos', 3785), ('ES', 'Valladolid', 3905),
        ('ES', 'Salamanca', 4030), ('PT', 'Guarda', 4190), ('PT', 'Coimbra', 4390),
        ('PT', 'Lisbon', 4610),
    ]
    stations = [dict(id=f'kyiv-lisbon/station/{i}', country=country, name=name,
                     position=km * 1000, positionStatus='estimated')
                for i, (country, name, km) in enumerate(itinerary)]
    length = stations[-1]['position']
    sections = []

    # Keep twelve sparse reduced zones. Long areas alternate 800 / 1500 m rails.
    zones = [
        (0, 6), (120, 132), (450, 470), (850, 858), (1280, 1296),
        (1720, 1744), (2180, 2192), (2830, 2846), (3300, 3306),
        (3810, 3822), (4230, 4240), (4598, 4610),
    ]

    def section(start, end, block):
        sections.append(dict(id=f'kyiv-lisbon/section/{start}', position=start,
                             length=end-start, block=block,
                             construction='jointed' if block == 'short-25' else 'long-rail',
                             railLengths=build_rails(end-start, block)))

    position, long_index = 0, 0
    for start_km, end_km in zones:
        start, end = start_km * 1000, end_km * 1000
        if start > position:
            section(position, start, ('long-800', 'long-1500')[long_index % 2])
            long_index += 1
        section(start, end, 'short-25')
        position = end
    if position < length:
        section(position, length, ('long-800', 'long-1500')[long_index % 2])

    # Speed annotations are independent scenario inputs, not generated by stations
    # or by inserting connector rails. Preserve the existing operating profile.
    approach_limits = [(300, 40), (580, 50), (680, 60), (930, 40), (1010, 50), (1210, 60), (1480, 40), (1600, 50), (1980, 60), (2200, 40), (2690, 50), (3270, 60), (3500, 40), (3505, 50), (3785, 60), (3905, 40), (4030, 50), (4190, 60), (4390, 40)]
    restrictions = [(0, 1000, 25), (length - 1000, length, 25)]
    restrictions += [((km - 1) * 1000, (km + 1) * 1000, speed)
                     for km, speed in approach_limits]
    restrictions += [(start * 1000, end * 1000, (60, 40, 50)[i % 3])
                     for i, (start, end) in enumerate(zones)]
    bounds = sorted({0, length} | {p for start, end, _ in restrictions for p in (start, end)})
    markers = []
    for start, end in zip(bounds, bounds[1:]):
        speed = min([260] + [limit for a, b, limit in restrictions if a <= start < b])
        if markers and markers[-1]['speedKmh'] == speed:
            markers[-1]['endPosition'] = end
        else:
            markers.append(dict(id=f'kyiv-lisbon/speed/{start}', type='speed_limit',
                                position=start, endPosition=end, speedKmh=speed,
                                status='estimated', basis='scenario-assumption'))
    return dict(id='kyiv-lisbon', name='Kyiv → Lisbon', length=length, synthetic=True,
                contactModel='rail-blocks-v1',
                description='4,610 km · varied track · approximate route',
                assumptions='City-level stops and scenario distances, not surveyed chainage. Borders, transfers and gauge changes are abstracted. Track construction and speeds are illustrative.',
                stations=stations, sections=sections, operatingMarkers=markers)


if __name__ == '__main__':
    output = ROOT / 'public/kyiv-lisbon.json'
    output.write_text(json.dumps(build_route(), ensure_ascii=False, indent=2) + '\n')
    print(f'{output.name}: {output.stat().st_size:,} bytes')
